// Generated by GitHub Copilot
import apiClient from '../api/client'

/**
 * Service d'accès aux endpoints de la carte des nourrices.
 *
 * - `GET /carte/nourrices?rayonKm=N` — nécessite un token Bearer (injecté par apiClient)
 * - `GET /carte/config` — retourne la clé JavaScript Google Maps
 */
export const carteService = {
  /**
   * Récupère les nourrices dans un rayon autour du parent connecté.
   *
   * @param {number} rayonKm - rayon de recherche en km (1–50, défaut : 10)
   * @returns {Promise} résolution : { positionParent, nourrices[] } | null si parent non géolocalisé
   */
  rechercherNourrices(rayonKm = 10) {
    return apiClient.get('/carte/nourrices', { params: { rayonKm } })
  },

  /**
   * Récupère la clé JavaScript Google Maps depuis le backend.
   *
   * @returns {Promise} résolution : { mapsJavascriptApiKey: string }
   */
  getConfig() {
    return apiClient.get('/carte/config')
  }
}
