// Generated by GitHub Copilot
import { describe, it, expect, vi, beforeEach } from 'vitest'

vi.mock('../src/api/client', () => ({
  default: {
    get: vi.fn()
  }
}))

import apiClient from '../src/api/client'
import { carteService } from '../src/services/carte.service'

describe('carteService', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  describe('rechercherNourrices()', () => {
    it('appelle GET /carte/nourrices avec le rayon par défaut (10)', () => {
      apiClient.get.mockResolvedValue({ data: {} })
      carteService.rechercherNourrices()
      expect(apiClient.get).toHaveBeenCalledWith('/carte/nourrices', { params: { rayonKm: 10 } })
    })

    it('appelle GET /carte/nourrices avec le rayon fourni', () => {
      apiClient.get.mockResolvedValue({ data: {} })
      carteService.rechercherNourrices(25)
      expect(apiClient.get).toHaveBeenCalledWith('/carte/nourrices', { params: { rayonKm: 25 } })
    })

    it('retourne la promesse résolue du client', async () => {
      const expected = { data: { positionParent: { latitude: 45.76, longitude: 4.83 }, nourrices: [] } }
      apiClient.get.mockResolvedValue(expected)
      await expect(carteService.rechercherNourrices(10)).resolves.toEqual(expected)
    })
  })

  describe('getConfig()', () => {
    it('appelle GET /carte/config', () => {
      apiClient.get.mockResolvedValue({ data: { mapsJavascriptApiKey: 'fake-key' } })
      carteService.getConfig()
      expect(apiClient.get).toHaveBeenCalledWith('/carte/config')
    })

    it('retourne la promesse résolue avec la clé API', async () => {
      const expected = { data: { mapsJavascriptApiKey: 'fake-key' } }
      apiClient.get.mockResolvedValue(expected)
      await expect(carteService.getConfig()).resolves.toEqual(expected)
    })
  })
})
