// Generated by GitHub Copilot
import { describe, it, expect, vi, beforeEach } from 'vitest'
import { setActivePinia, createPinia } from 'pinia'

vi.mock('../src/services/carte.service', () => ({
  carteService: {
    rechercherNourrices: vi.fn(),
    getConfig: vi.fn()
  }
}))

import { carteService } from '../src/services/carte.service'
import { useCarteStore } from '../src/stores/carte'

const uneNourrice = (id = 'n1') => ({
  id,
  nom: 'Martin',
  prenom: 'Sophie',
  adresse: '5 rue des Roses',
  codePostal: '69001',
  ville: 'Lyon',
  latitude: 45.76,
  longitude: 4.84,
  distanceKm: 0.8
})

describe('carte store', () => {
  beforeEach(() => {
    setActivePinia(createPinia())
    vi.clearAllMocks()
  })

  describe('état initial', () => {
    it('initialise le state avec des valeurs vides', () => {
      const store = useCarteStore()
      expect(store.positionParent).toBeNull()
      expect(store.nourrices).toEqual([])
      expect(store.mapsApiKey).toBeNull()
      expect(store.rayonKm).toBe(10)
      expect(store.chargement).toBe(false)
      expect(store.erreur).toBeNull()
    })
  })

  describe('getters', () => {
    it('parentGeolocalise retourne false si positionParent est null', () => {
      const store = useCarteStore()
      expect(store.parentGeolocalise).toBe(false)
    })

    it('parentGeolocalise retourne true si positionParent est défini', () => {
      const store = useCarteStore()
      store.positionParent = { latitude: 45.76, longitude: 4.83 }
      expect(store.parentGeolocalise).toBe(true)
    })

    it('nombreNourrices retourne la longueur du tableau', () => {
      const store = useCarteStore()
      store.nourrices = [uneNourrice('n1'), uneNourrice('n2')]
      expect(store.nombreNourrices).toBe(2)
    })
  })

  describe('action chargerConfig()', () => {
    it('charge la clé API depuis le backend', async () => {
      carteService.getConfig.mockResolvedValue({ data: { mapsJavascriptApiKey: 'fake-key' } })
      const store = useCarteStore()

      await store.chargerConfig()

      expect(store.mapsApiKey).toBe('fake-key')
    })

    it('est idempotent : ne rappelle pas le service si la clé est déjà présente', async () => {
      const store = useCarteStore()
      store.mapsApiKey = 'already-loaded'

      await store.chargerConfig()

      expect(carteService.getConfig).not.toHaveBeenCalled()
    })

    it('positionne erreur si le service échoue', async () => {
      carteService.getConfig.mockRejectedValue(new Error('network'))
      const store = useCarteStore()

      await store.chargerConfig()

      expect(store.mapsApiKey).toBeNull()
      expect(store.erreur).toContain('Google Maps')
    })
  })

  describe('action rechercherNourrices()', () => {
    it('charge positionParent et nourrices depuis le service', async () => {
      const positionParent = { latitude: 45.76, longitude: 4.83 }
      carteService.rechercherNourrices.mockResolvedValue({
        status: 200,
        data: { positionParent, nourrices: [uneNourrice()] }
      })
      const store = useCarteStore()

      const result = await store.rechercherNourrices()

      expect(result).toBe(true)
      expect(store.positionParent).toEqual(positionParent)
      expect(store.nourrices).toHaveLength(1)
      expect(store.chargement).toBe(false)
    })

    it('met à jour rayonKm si fourni en paramètre', async () => {
      carteService.rechercherNourrices.mockResolvedValue({
        status: 200,
        data: { positionParent: { latitude: 45, longitude: 4 }, nourrices: [] }
      })
      const store = useCarteStore()

      await store.rechercherNourrices(25)

      expect(store.rayonKm).toBe(25)
      expect(carteService.rechercherNourrices).toHaveBeenCalledWith(25)
    })

    it('retourne false et vide le state si le parent n\'est pas géolocalisé (204)', async () => {
      carteService.rechercherNourrices.mockResolvedValue({ status: 204, data: null })
      const store = useCarteStore()
      store.nourrices = [uneNourrice()]

      const result = await store.rechercherNourrices()

      expect(result).toBe(false)
      expect(store.positionParent).toBeNull()
      expect(store.nourrices).toEqual([])
    })

    it('positionne erreur et retourne false en cas d\'échec réseau', async () => {
      carteService.rechercherNourrices.mockRejectedValue({ response: { data: { message: 'token invalide' } } })
      const store = useCarteStore()

      const result = await store.rechercherNourrices()

      expect(result).toBe(false)
      expect(store.erreur).toBe('token invalide')
      expect(store.chargement).toBe(false)
    })

    it('positionne un message générique si la réponse d\'erreur ne contient pas de message', async () => {
      carteService.rechercherNourrices.mockRejectedValue(new Error('network'))
      const store = useCarteStore()

      await store.rechercherNourrices()

      expect(store.erreur).toBeTruthy()
    })
  })

  describe('action reinitialiser()', () => {
    it('remet le store dans son état initial', () => {
      const store = useCarteStore()
      store.positionParent = { latitude: 1, longitude: 2 }
      store.nourrices = [uneNourrice()]
      store.rayonKm = 25
      store.erreur = 'une erreur'

      store.reinitialiser()

      expect(store.positionParent).toBeNull()
      expect(store.nourrices).toEqual([])
      expect(store.rayonKm).toBe(10)
      expect(store.erreur).toBeNull()
    })
  })
})
