// Generated by GitHub Copilot
import { defineStore } from 'pinia'
import { carteService } from '../services/carte.service'

/**
 * Store Pinia pour la carte des nourrices.
 *
 * États :
 * - positionParent  : { latitude, longitude } | null
 * - nourrices       : NourriceSurCarte[]
 * - mapsApiKey      : clé JavaScript Google Maps (chargée une seule fois)
 * - rayonKm         : rayon de recherche courant
 * - chargement      : boolean (requête en cours)
 * - erreur          : string | null
 */
export const useCarteStore = defineStore('carte', {
  state: () => ({
    positionParent: null,
    nourrices: [],
    mapsApiKey: null,
    rayonKm: 10,
    chargement: false,
    erreur: null
  }),

  getters: {
    /** Vrai si le parent a une position géolocalisée */
    parentGeolocalise: (state) => !!state.positionParent,

    /** Nombre de nourrices trouvées */
    nombreNourrices: (state) => state.nourrices.length
  },

  actions: {
    /**
     * Charge la clé JavaScript Google Maps depuis le backend (une seule fois).
     * Idempotent : ne refait pas l'appel si la clé est déjà présente.
     */
    async chargerConfig() {
      if (this.mapsApiKey) return
      try {
        const response = await carteService.getConfig()
        this.mapsApiKey = response.data.mapsJavascriptApiKey
      } catch (e) {
        this.erreur = 'Impossible de charger la configuration Google Maps'
      }
    },

    /**
     * Recherche les nourrices dans le rayon courant autour du parent connecté.
     * Met à jour positionParent et nourrices. Renvoie false si le parent
     * n'est pas encore géolocalisé (HTTP 204).
     *
     * @param {number} [rayonKm] - optionnel, remplace rayonKm du state
     * @returns {Promise<boolean>} true si des données ont été chargées
     */
    async rechercherNourrices(rayonKm) {
      if (rayonKm !== undefined) this.rayonKm = rayonKm
      this.chargement = true
      this.erreur = null
      try {
        const response = await carteService.rechercherNourrices(this.rayonKm)
        if (response.status === 204 || !response.data) {
          this.positionParent = null
          this.nourrices = []
          return false
        }
        this.positionParent = response.data.positionParent
        this.nourrices = response.data.nourrices
        return true
      } catch (e) {
        this.erreur = e.response?.data?.message ?? 'Erreur lors de la recherche de nourrices'
        return false
      } finally {
        this.chargement = false
      }
    },

    /** Remet le store dans son état initial */
    reinitialiser() {
      this.positionParent = null
      this.nourrices = []
      this.rayonKm = 10
      this.chargement = false
      this.erreur = null
    }
  }
})
