<template>
  <div class="carte-nourrices">
    <div class="carte-header">
      <h2>🗺️ Carte des Nourrices</h2>
      <div class="rayon-selector">
        <label for="rayon">Rayon&nbsp;:</label>
        <select id="rayon" v-model.number="rayonSelectionne" @change="onRayonChange" :disabled="carteStore.chargement">
          <option :value="5">5 km</option>
          <option :value="10">10 km</option>
          <option :value="20">20 km</option>
          <option :value="50">50 km</option>
        </select>
      </div>
    </div>

    <div v-if="carteStore.erreur" class="message-erreur" role="alert">
      ⚠️ {{ carteStore.erreur }}
    </div>

    <div v-if="carteStore.chargement" class="chargement" aria-live="polite">
      Chargement de la carte…
    </div>

    <div
      v-else-if="!carteStore.parentGeolocalise"
      class="message-info"
      role="status"
    >
      <p>📍 Votre position n'est pas encore géolocalisée.</p>
      <p>Elle sera calculée automatiquement quelques instants après votre inscription.</p>
    </div>

    <template v-else>
      <p class="compteur" role="status" aria-live="polite">
        {{ carteStore.nombreNourrices }} nourrice{{ carteStore.nombreNourrices !== 1 ? 's' : '' }}
        trouvée{{ carteStore.nombreNourrices !== 1 ? 's' : '' }}
        dans un rayon de {{ carteStore.rayonKm }} km
      </p>

      <!-- Conteneur de la carte Google Maps -->
      <div
        ref="mapContainer"
        class="map-container"
        aria-label="Carte des nourrices disponibles près de chez vous"
        role="img"
      ></div>

      <!-- Liste accessible des nourrices (alternative textuelle à la carte) -->
      <section class="nourrices-list" aria-label="Liste des nourrices sur la carte">
        <h3 class="sr-only">Nourrices disponibles</h3>
        <ul>
          <li
            v-for="nourrice in carteStore.nourrices"
            :key="nourrice.id"
            class="nourrice-item"
          >
            <strong>{{ nourrice.prenom }} {{ nourrice.nom }}</strong>
            <span>{{ nourrice.adresse }}, {{ nourrice.codePostal }} {{ nourrice.ville }}</span>
            <span class="distance">à {{ nourrice.distanceKm.toFixed(1) }} km</span>
          </li>
        </ul>
      </section>
    </template>
  </div>
</template>

<script>
// Generated by GitHub Copilot
import { defineComponent, ref, onMounted, onUnmounted, watch } from 'vue'
import { setOptions, importLibrary } from '@googlemaps/js-api-loader'
import { useCarteStore } from '../stores/carte'

// setOptions ne doit être appelé qu'une seule fois par session de page
let mapsApiInitialized = false

export default defineComponent({
  name: 'CarteNourrices',

  setup() {
    const carteStore = useCarteStore()
    const mapContainer = ref(null)
    const rayonSelectionne = ref(carteStore.rayonKm)

    let mapInstance = null
    let marqueurs = []

    /** Initialise ou met à jour la carte Google Maps avec les données du store. */
    async function initialiserCarte() {
      if (!carteStore.mapsApiKey || !carteStore.parentGeolocalise || !mapContainer.value) return

      if (!mapsApiInitialized) {
        setOptions({
          key: carteStore.mapsApiKey,
          version: 'weekly'
        })
        mapsApiInitialized = true
      }

      const { Map } = await importLibrary('maps')
      const { AdvancedMarkerElement } = await importLibrary('marker')

      const centre = {
        lat: carteStore.positionParent.latitude,
        lng: carteStore.positionParent.longitude
      }

      if (!mapInstance) {
        mapInstance = new Map(mapContainer.value, {
          center: centre,
          zoom: rayonVersZoom(carteStore.rayonKm),
          mapId: carteStore.mapsMapId || undefined
        })
      } else {
        mapInstance.setCenter(centre)
        mapInstance.setZoom(rayonVersZoom(carteStore.rayonKm))
      }

      // Supprime les anciens marqueurs
      marqueurs.forEach(m => { m.map = null })
      marqueurs = []

      // Marqueur de la position du parent
      const parentEl = document.createElement('div')
      parentEl.className = 'marker marker--parent'
      parentEl.innerHTML = `
        <div class="marker__pin">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" width="18" height="18" aria-hidden="true">
            <path d="M12 12c2.7 0 4.8-2.1 4.8-4.8S14.7 2.4 12 2.4 7.2 4.5 7.2 7.2 9.3 12 12 12zm0 2.4c-3.2 0-9.6 1.6-9.6 4.8v2.4h19.2v-2.4c0-3.2-6.4-4.8-9.6-4.8z"/>
          </svg>
        </div>
        <div class="marker__label">Vous</div>
      `
      const markerParent = new AdvancedMarkerElement({
        map: mapInstance,
        position: centre,
        title: 'Votre position',
        content: parentEl
      })
      marqueurs.push(markerParent)

      // Marqueurs des nourrices
      for (const nourrice of carteStore.nourrices) {
        const nourriceEl = document.createElement('div')
        nourriceEl.className = 'marker marker--nourrice'
        nourriceEl.innerHTML = `
          <div class="marker__pin">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" width="18" height="18" aria-hidden="true">
              <path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5c-1.38 0-2.5-1.12-2.5-2.5s1.12-2.5 2.5-2.5 2.5 1.12 2.5 2.5-1.12 2.5-2.5 2.5z"/>
            </svg>
          </div>
          <div class="marker__label">${nourrice.prenom}</div>
        `
        const marker = new AdvancedMarkerElement({
          map: mapInstance,
          position: { lat: nourrice.latitude, lng: nourrice.longitude },
          title: `${nourrice.prenom} ${nourrice.nom} – ${nourrice.distanceKm.toFixed(1)} km`,
          content: nourriceEl
        })
        marqueurs.push(marker)
      }
    }

    /** Convertit un rayon en km en niveau de zoom approximatif. */
    function rayonVersZoom(rayonKm) {
      if (rayonKm <= 5)  return 13
      if (rayonKm <= 10) return 12
      if (rayonKm <= 20) return 11
      return 10
    }

    async function chargerDonnees() {
      await carteStore.chargerConfig()
      await carteStore.rechercherNourrices(rayonSelectionne.value)
    }

    async function onRayonChange() {
      await carteStore.rechercherNourrices(rayonSelectionne.value)
    }

    onMounted(async () => {
      await chargerDonnees()
      await initialiserCarte()
    })

    onUnmounted(() => {
      marqueurs.forEach(m => { m.map = null })
      mapInstance = null
    })

    // Réinitialise la carte quand les nourrices changent (changement de rayon)
    watch(() => carteStore.nourrices, async () => {
      await initialiserCarte()
    })

    // Quand le conteneur est remonté dans le DOM (après v-else), force la réinitialisation
    watch(mapContainer, async (newContainer) => {
      if (newContainer && carteStore.parentGeolocalise) {
        mapInstance = null
        await initialiserCarte()
      }
    })

    return { carteStore, mapContainer, rayonSelectionne, onRayonChange }
  }
})
</script>

<style scoped>
.carte-nourrices {
  padding: 20px;
}

.carte-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-wrap: wrap;
  gap: 12px;
  margin-bottom: 16px;
}

.carte-header h2 {
  margin: 0;
}

.rayon-selector {
  display: flex;
  align-items: center;
  gap: 8px;
}

.rayon-selector select {
  padding: 6px 10px;
  border: 1px solid #ccc;
  border-radius: 6px;
  font-size: 0.95rem;
  cursor: pointer;
}

.rayon-selector select:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.map-container {
  width: 100%;
  height: 480px;
  border-radius: 12px;
  overflow: hidden;
  border: 1px solid #ddd;
  margin-bottom: 20px;
}

/* ---- Marqueurs carte ---- */
:deep(.marker) {
  display: flex;
  flex-direction: column;
  align-items: center;
  cursor: pointer;
  filter: drop-shadow(0 2px 4px rgba(0,0,0,.35));
}

:deep(.marker__pin) {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 36px;
  height: 36px;
  border-radius: 50% 50% 50% 0;
  transform: rotate(-45deg);
  color: #fff;
}

:deep(.marker__pin svg) {
  transform: rotate(45deg);
  flex-shrink: 0;
}

:deep(.marker--parent .marker__pin) {
  background: #1a73e8;
}

:deep(.marker--nourrice .marker__pin) {
  background: #e8710a;
}

:deep(.marker__label) {
  margin-top: 2px;
  font-size: 11px;
  font-weight: 600;
  white-space: nowrap;
  padding: 1px 5px;
  border-radius: 4px;
  background: rgba(255,255,255,.9);
  box-shadow: 0 1px 3px rgba(0,0,0,.2);
  line-height: 1.4;
}

:deep(.marker--parent .marker__label) {
  color: #1a73e8;
}

:deep(.marker--nourrice .marker__label) {
  color: #e8710a;
}

.compteur {
  margin-bottom: 8px;
  color: #555;
  font-size: 0.9rem;
}

.chargement {
  padding: 40px;
  text-align: center;
  color: #888;
}

.message-info {
  padding: 24px;
  background-color: #f0f4ff;
  border-radius: 8px;
  text-align: center;
  color: #444;
}

.message-erreur {
  padding: 12px 16px;
  background-color: #fff3cd;
  border: 1px solid #ffc107;
  border-radius: 6px;
  color: #856404;
  margin-bottom: 12px;
}

.nourrices-list ul {
  list-style: none;
  padding: 0;
  margin: 0;
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
  gap: 12px;
}

.nourrice-item {
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding: 12px 16px;
  background-color: white;
  border-radius: 8px;
  box-shadow: 0 1px 4px rgba(0, 0, 0, 0.1);
  font-size: 0.9rem;
}

.distance {
  color: #4a90e2;
  font-weight: 600;
}

/* Classe utilitaire d'accessibilité : masque visuellement sans cacher aux lecteurs d'écran */
.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border-width: 0;
}
</style>
