<template>
  <div class="carte-nourrices">
    <div class="carte-header">
      <h2>🗺️ Carte des Nourrices</h2>
      <div class="rayon-selector">
        <label for="rayon">Rayon&nbsp;:</label>
        <select id="rayon" v-model.number="rayonSelectionne" @change="onRayonChange" :disabled="carteStore.chargement">
          <option :value="5">5 km</option>
          <option :value="10">10 km</option>
          <option :value="20">20 km</option>
          <option :value="50">50 km</option>
        </select>
      </div>
    </div>

    <div v-if="carteStore.erreur" class="message-erreur" role="alert">
      ⚠️ {{ carteStore.erreur }}
    </div>

    <div v-if="carteStore.chargement" class="chargement" aria-live="polite">
      Chargement de la carte…
    </div>

    <div
      v-else-if="!carteStore.parentGeolocalise"
      class="message-info"
      role="status"
    >
      <p>📍 Votre position n'est pas encore géolocalisée.</p>
      <p>Elle sera calculée automatiquement quelques instants après votre inscription.</p>
    </div>

    <template v-else>
      <p class="compteur" role="status" aria-live="polite">
        {{ carteStore.nombreNourrices }} nourrice{{ carteStore.nombreNourrices !== 1 ? 's' : '' }}
        trouvée{{ carteStore.nombreNourrices !== 1 ? 's' : '' }}
        dans un rayon de {{ carteStore.rayonKm }} km
      </p>

      <!-- Conteneur de la carte Google Maps -->
      <div
        ref="mapContainer"
        class="map-container"
        aria-label="Carte des nourrices disponibles près de chez vous"
        role="img"
      ></div>

      <!-- Liste accessible des nourrices (alternative textuelle à la carte) -->
      <section class="nourrices-list" aria-label="Liste des nourrices sur la carte">
        <h3 class="sr-only">Nourrices disponibles</h3>
        <ul>
          <li
            v-for="nourrice in carteStore.nourrices"
            :key="nourrice.id"
            class="nourrice-item"
          >
            <strong>{{ nourrice.prenom }} {{ nourrice.nom }}</strong>
            <span>{{ nourrice.adresse }}, {{ nourrice.codePostal }} {{ nourrice.ville }}</span>
            <span class="distance">à {{ nourrice.distanceKm.toFixed(1) }} km</span>
          </li>
        </ul>
      </section>
    </template>
  </div>
</template>

<script>
// Generated by GitHub Copilot
import { defineComponent, ref, onMounted, onUnmounted, watch } from 'vue'
import { Loader } from '@googlemaps/js-api-loader'
import { useCarteStore } from '../stores/carte'

export default defineComponent({
  name: 'CarteNourrices',

  setup() {
    const carteStore = useCarteStore()
    const mapContainer = ref(null)
    const rayonSelectionne = ref(carteStore.rayonKm)

    let mapInstance = null
    let marqueurs = []

    /** Initialise ou met à jour la carte Google Maps avec les données du store. */
    async function initialiserCarte() {
      if (!carteStore.mapsApiKey || !carteStore.parentGeolocalise || !mapContainer.value) return

      const loader = new Loader({
        apiKey: carteStore.mapsApiKey,
        version: 'weekly',
        libraries: ['maps', 'marker']
      })

      const { Map } = await loader.importLibrary('maps')
      const { AdvancedMarkerElement } = await loader.importLibrary('marker')

      const centre = {
        lat: carteStore.positionParent.latitude,
        lng: carteStore.positionParent.longitude
      }

      if (!mapInstance) {
        mapInstance = new Map(mapContainer.value, {
          center: centre,
          zoom: rayonVersZoom(carteStore.rayonKm),
          mapId: 'aleo-carte-nourrices'
        })
      } else {
        mapInstance.setCenter(centre)
        mapInstance.setZoom(rayonVersZoom(carteStore.rayonKm))
      }

      // Supprime les anciens marqueurs
      marqueurs.forEach(m => { m.map = null })
      marqueurs = []

      // Marqueur de la position du parent
      const markerParent = new AdvancedMarkerElement({
        map: mapInstance,
        position: centre,
        title: 'Votre position'
      })
      markerParent.content.style.cssText = 'font-size:28px'
      markerParent.content.innerHTML = '📍'
      marqueurs.push(markerParent)

      // Marqueurs des nourrices
      for (const nourrice of carteStore.nourrices) {
        const marker = new AdvancedMarkerElement({
          map: mapInstance,
          position: { lat: nourrice.latitude, lng: nourrice.longitude },
          title: `${nourrice.prenom} ${nourrice.nom} – ${nourrice.distanceKm.toFixed(1)} km`
        })
        marker.content.style.cssText = 'font-size:24px'
        marker.content.innerHTML = '🧒'
        marqueurs.push(marker)
      }
    }

    /** Convertit un rayon en km en niveau de zoom approximatif. */
    function rayonVersZoom(rayonKm) {
      if (rayonKm <= 5)  return 13
      if (rayonKm <= 10) return 12
      if (rayonKm <= 20) return 11
      return 10
    }

    async function chargerDonnees() {
      await carteStore.chargerConfig()
      await carteStore.rechercherNourrices(rayonSelectionne.value)
    }

    async function onRayonChange() {
      await carteStore.rechercherNourrices(rayonSelectionne.value)
    }

    onMounted(async () => {
      await chargerDonnees()
      await initialiserCarte()
    })

    onUnmounted(() => {
      marqueurs.forEach(m => { m.map = null })
      mapInstance = null
    })

    // Réinitialise la carte quand les nourrices changent (changement de rayon)
    watch(() => carteStore.nourrices, async () => {
      await initialiserCarte()
    })

    return { carteStore, mapContainer, rayonSelectionne, onRayonChange }
  }
})
</script>

<style scoped>
.carte-nourrices {
  padding: 20px;
}

.carte-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-wrap: wrap;
  gap: 12px;
  margin-bottom: 16px;
}

.carte-header h2 {
  margin: 0;
}

.rayon-selector {
  display: flex;
  align-items: center;
  gap: 8px;
}

.rayon-selector select {
  padding: 6px 10px;
  border: 1px solid #ccc;
  border-radius: 6px;
  font-size: 0.95rem;
  cursor: pointer;
}

.rayon-selector select:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.map-container {
  width: 100%;
  height: 480px;
  border-radius: 12px;
  overflow: hidden;
  border: 1px solid #ddd;
  margin-bottom: 20px;
}

.compteur {
  margin-bottom: 8px;
  color: #555;
  font-size: 0.9rem;
}

.chargement {
  padding: 40px;
  text-align: center;
  color: #888;
}

.message-info {
  padding: 24px;
  background-color: #f0f4ff;
  border-radius: 8px;
  text-align: center;
  color: #444;
}

.message-erreur {
  padding: 12px 16px;
  background-color: #fff3cd;
  border: 1px solid #ffc107;
  border-radius: 6px;
  color: #856404;
  margin-bottom: 12px;
}

.nourrices-list ul {
  list-style: none;
  padding: 0;
  margin: 0;
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
  gap: 12px;
}

.nourrice-item {
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding: 12px 16px;
  background-color: white;
  border-radius: 8px;
  box-shadow: 0 1px 4px rgba(0, 0, 0, 0.1);
  font-size: 0.9rem;
}

.distance {
  color: #4a90e2;
  font-weight: 600;
}

/* Classe utilitaire d'accessibilité : masque visuellement sans cacher aux lecteurs d'écran */
.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border-width: 0;
}
</style>
